In [32]:
import pandas
import numpy
import time

In [33]:
# data_read = pandas.read_csv('x-ANACONDA/NLU-DH21HM/Week04-Sequence_Array/Exercise/IP04-exercise.csv')
data_read = pandas.read_csv('IP04-exercise.csv')
data_read.head()
# print(data_read.head())
# data_read.info()

NOC  Gold  Silver  Bronze  Total
0  Austria     5       3       6     14
1   Canada    11       8      10     29
2   France     5       4       6     15
3  Germany    14      10       7     31
4    Italy     3       2       5     10

In [34]:
countries = data_read[['NOC']]
# countries
gold = data_read[['Gold']]
# gold
silver = data_read[['Silver']]
# silver
bronze = data_read[['Bronze']]
# bronze

In [64]:
countries = data_read.NOC.values
print(countries)
gold = data_read.Gold.values
print(gold)
silver = data_read.Silver.values
print(silver)
bronze = data_read.Bronze.values
print(bronze)

['Austria' 'Canada' 'France' 'Germany' 'Italy' 'Japan' 'Netherlands'
 'Norway' 'Russia' 'South Korea' 'Sweden' 'Swizerland' 'United State']
[ 5 11  5 14  3  4  8 14  2  5  7  5  9]
[ 3  8  4 10  2  5  6 14  6  8  6  6  8]
[ 6 10  6  7  5  4  6 11  9  4  1  4  6]


In [66]:
gold_sum = []
def medal_compute(gold, silver, bronze):
    for i in range(len(gold)):
        gold_sum.append(gold[i] + silver[i]/2 + bronze[i]/3)
    return gold_sum

# gold_sum = numpy.random.random(len(gold))
# def medal_compute(gold, silver, bronze):
#     for i in range(len(gold)):
#         gold_sum[i] = gold[i] + silver[i]/2 + bronze[i]/3
#     return gold_sum

In [67]:
medal_sum = medal_compute(gold, silver, bronze)
medal_sum = numpy.round(medal_sum, 2)
medal_sum

array([ 8.5 , 18.33,  9.  , 21.33,  5.67,  7.83, 13.  , 24.67,  8.  ,
       10.33, 10.33,  9.33, 15.  ])

In [80]:
sort_list = []
for i in range(len(countries)):
#     sort_list.append((countries[i], medal_sum[i]))
    sort_list.append((medal_sum[i], countries[i]))
# sort_list

In [83]:
sort_list.sort()
sort_list

[(5.67, 'Italy'),
 (7.83, 'Japan'),
 (8.0, 'Russia'),
 (8.5, 'Austria'),
 (9.0, 'France'),
 (9.33, 'Swizerland'),
 (10.33, 'South Korea'),
 (10.33, 'Sweden'),
 (13.0, 'Netherlands'),
 (15.0, 'United State'),
 (18.33, 'Canada'),
 (21.33, 'Germany'),
 (24.67, 'Norway')]

In [84]:
end_list = len(sort_list)
rank_123 = sort_list[(end_list-3):end_list]
print(rank_123)

[(18.33, 'Canada'), (21.33, 'Germany'), (24.67, 'Norway')]


In [88]:
print("Country with 3rd ranking: ", sort_list[(end_list-3):(end_list-2)])
print("Country with 2nd ranking: ", sort_list[(end_list-2):(end_list-1)])
print("Country with 1st ranking: ", sort_list[(end_list-1):(end_list-0)])

Country with 3rd ranking:  [(18.33, 'Canada')]
Country with 2nd ranking:  [(21.33, 'Germany')]
Country with 1st ranking:  [(24.67, 'Norway')]


In [103]:
dict_save = {'rank': rank_123}
# pandas.DataFrame(dict_save).to_csv('IP04-exercise-save.csv')
pandas.DataFrame(dict_save).to_csv('IP04-exercise-save.csv', header=True, index=False)