In [1]:
import numpy as np

In [12]:
arr1 = np.random.random((5,4))
print(arr1)

[[0.63074519 0.7123047  0.02907602 0.3582527 ]
 [0.71231421 0.4578486  0.69616634 0.06185461]
 [0.86458739 0.73316716 0.47437676 0.77506726]
 [0.57810407 0.97283457 0.99997605 0.63259825]
 [0.01789015 0.1765616  0.98234932 0.46844864]]


In [25]:
arr1 = np.random.random((6,8))
print(arr1)

[[0.66370816 0.29225125 0.19083547 0.2212626  0.32866637 0.44205094
  0.91637942 0.69944004]
 [0.02471647 0.24089615 0.54598998 0.2778482  0.51312677 0.43316308
  0.33547976 0.38773663]
 [0.50821676 0.96294773 0.51435582 0.60735924 0.99709421 0.73975644
  0.17221691 0.92991127]
 [0.87775935 0.85471122 0.69754287 0.27738841 0.32851053 0.46561877
  0.35962681 0.32816513]
 [0.98648942 0.81358778 0.38677979 0.76801879 0.31989914 0.18893984
  0.81903558 0.95276269]
 [0.34961905 0.15611354 0.98118599 0.66266744 0.79645928 0.25919938
  0.73948868 0.55302167]]


In [28]:
print(arr1[2][3])

0.6073592435600461


In [23]:
arr1 = np.array([[1, 2, 3], [2,3,1]])
print(arr1)
arr2 = arr1.T
print(arr2)

[[1 2 3]
 [2 3 1]]
[[1 2]
 [2 3]
 [3 1]]
