In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6)
print(arr1)

[0 1 2 3 4 5]


In [3]:
arr1 = np.arange(6).reshape(3,2)
print(arr1)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
import scipy
import numpy

In [6]:
arr = numpy.array([[1, 0, 0], [0,0,0], [0,0,3]])
arr

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 3]])

In [8]:
sparse_arr = scipy.sparse.csr_matrix(arr)

AttributeError: module 'numpy' has no attribute 'sparse'