In [2]:
import numpy as np

In [4]:
vector = np.array([1,3,5,7,9,11,13,15])
vector

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [7]:
vec_transpose = vector.T
vec_transpose

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [5]:
matrix = np.array( [ [1,3,5], [7,9,11], [13,15,17] ] )
matrix

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [8]:
matrix_transpose = matrix.T
matrix_transpose

array([[ 1,  7, 13],
       [ 3,  9, 15],
       [ 5, 11, 17]])

In [6]:
# error with size of matrix
matrix2 = np.array( [ [1,3,5], [7,9,11], [13,15,17,19] ] )
matrix2

C:\Users\dinhl\AppData\Local\Temp\ipykernel_18088\2881831747.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matrix2 = np.array( [ [1,3,5], [7,9,11], [13,15,17,19] ] )


array([list([1, 3, 5]), list([7, 9, 11]), list([13, 15, 17, 19])],
      dtype=object)

In [12]:
# matrix with randomness and indexing
arr1 = np.random.random((5,4))
print(arr1)
print(arr1[2]) # 3rd row
print(arr1[2][3]) # accessing element
print(arr1[2,3])

[[0.13563463 0.38755699 0.15519904 0.99662919]
 [0.71208985 0.41475593 0.99076433 0.91798074]
 [0.63168753 0.96849647 0.62357794 0.5704042 ]
 [0.83961853 0.46487818 0.84271211 0.40823876]
 [0.40088142 0.4106487  0.53997456 0.67075824]]
[0.63168753 0.96849647 0.62357794 0.5704042 ]
0.5704041958023962
0.5704041958023962


In [16]:
matrix_A = np.array([[1,2,3], [4,5,6]], dtype=int)
print(matrix_A)
matrix_B = np.array([[1,2,3], [4,5,6]], dtype=float)
print(matrix_B)
matrix_C = np.array([[1,2,3], [4,5,6]], dtype=complex)
print(matrix_C)

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [18]:
mat_1 = np.zeros( (2,4))
print(mat_1)
mat_2 = np.zeros( (2,4), dtype=np.int32 )
print(mat_2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]]


In [19]:
mat_3 = np.ones( (2,4), dtype=np.int32 )
print(mat_3)

[[1 1 1 1]
 [1 1 1 1]]


In [22]:
mat_3 = np.eye(4, dtype=int )
print(mat_3)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
