In [1]:
import numpy as np

In [2]:
arr1 = np.arange(6)
print(arr1)

[0 1 2 3 4 5]


In [3]:
arr1 = np.arange(6).reshape(3,2)
print(arr1)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
arr = np.array([[1, 0, 0], [0,0,0], [0,0,3]])
arr

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 3]])

In [16]:
mat_a = np.random.random((2,3))
print(mat_a)
mat_b = np.random.random((2,3))
print(mat_b)
mat_c = mat_a + mat_b
print(mat_c)

mat_c2 = np.add(mat_a, mat_b)
print(mat_c2)

[[0.02485729 0.21341185 0.20973404]
 [0.87399679 0.88871006 0.59291031]]
[[0.48472597 0.13827441 0.12827444]
 [0.5339554  0.63681073 0.33538177]]
[[0.50958326 0.35168626 0.33800849]
 [1.40795219 1.5255208  0.92829208]]
[[0.50958326 0.35168626 0.33800849]
 [1.40795219 1.5255208  0.92829208]]


In [10]:
# error with matrix size
mat_d = np.random.random((3,3))
mat_e = mat_a + mat_d
print(mat_e)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [13]:
mat_c = mat_a.dot(mat_b.T)
print(mat_c)

[[0.85351188 0.70472331]
 [1.07173446 1.30307539]]


In [15]:
# error with matrix size
mat_c = mat_a.dot(mat_b)
print(mat_c)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
mat_a2 = 5*mat_a
print(mat_a2)

[[0.12428644 1.06705925 1.0486702 ]
 [4.36998394 4.44355031 2.96455154]]


In [21]:
mat_i = np.random.random((2,3))
print(mat_i)

print(np.mean(mat_i))
print(np.var(mat_i))
print(np.std(mat_i))

[[0.97032259 0.04921482 0.79353168]
 [0.46719402 0.09984587 0.59460247]]
0.49578524158518267
0.11343567760742641
0.33680213420853855
