In [1]:
import numpy as np

In [4]:
# svd array
mat_1 = np.random.random((4,4))
mat_1

array([[0.93632101, 0.5972533 , 0.86560726, 0.89657234],
       [0.66663779, 0.36324632, 0.58289472, 0.05059645],
       [0.58698579, 0.83856151, 0.66011538, 0.8340055 ],
       [0.49529882, 0.01355795, 0.07489884, 0.95839386]])

In [8]:
u, s, vh = np.linalg.svd(mat_1, full_matrices=True)
print(u)
print(s)
print(vh)

[[-0.66677721 -0.0732488   0.22001371 -0.70826318]
 [-0.32414645 -0.5762248   0.53125063  0.52977999]
 [-0.57708616 -0.07287868 -0.74856769  0.31828708]
 [-0.34250372  0.81073318  0.33017139  0.34115944]]
[2.49613324 0.79773746 0.42201348 0.0934531 ]
[[-0.5403513  -0.40244077 -0.46980947 -0.57038668]
 [-0.11775951 -0.3800511  -0.48470639  0.77894388]
 [ 0.6736517  -0.70818793  0.07273951 -0.19842432]
 [ 0.49025153  0.4382607  -0.73419871 -0.1689179 ]]


In [9]:
u.shape, s.shape, vh.shape

((4, 4), (4,), (4, 4))

In [11]:
evalues, evectors = np.linalg.eig(mat_1)
print(evalues)
print(evectors)

[ 2.36403987+0.j         -0.1140368 +0.17166767j -0.1140368 -0.17166767j
  0.78211031+0.j        ]
[[ 0.67550627+0.j         -0.30804834-0.28789448j -0.30804834+0.28789448j
  -0.19442151+0.j        ]
 [ 0.39512629+0.j         -0.50991889+0.20358099j -0.50991889-0.20358099j
  -0.61326329+0.j        ]
 [ 0.56013886+0.j          0.70321443+0.j          0.70321443-0.j
  -0.28017665+0.j        ]
 [ 0.27168171+0.j          0.07676612+0.14267768j  0.07676612-0.14267768j
   0.71246716+0.j        ]]
